#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("KeepOnDroning.Droid.Resource", IsApplication=true)]

namespace KeepOnDroning.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::KeepOnDroning.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::KeepOnDroning.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::KeepOnDroning.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::KeepOnDroning.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::KeepOnDroning.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::KeepOnDroning.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::KeepOnDroning.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::KeepOnDroning.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::KeepOnDroning.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::KeepOnDroning.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::KeepOnDroning.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::KeepOnDroning.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::KeepOnDroning.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::KeepOnDroning.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::KeepOnDroning.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::KeepOnDroning.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::KeepOnDroning.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::KeepOnDroning.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::KeepOnDroning.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::KeepOnDroning.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::KeepOnDroning.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int black_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int blue_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int blue_light_color = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int grey_color = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int grey_light_color = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int orange_color = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int red_color = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int transparent = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int white_color = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int whitebox_color = 2131099656;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ComputerSaysNo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int GameButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GreenButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IMG_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IMG_birds_negative = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IMG_birds_positive = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IMG_check_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IMG_game_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IMG_info_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IMG_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IMG_map_view_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IMG_noflyzones_negative = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IMG_noflyzones_positive = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IMG_otherobjects_negative = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IMG_otherobjects_positive = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IMG_waypoints_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IMG_weather_negative = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int IMG_weather_positive = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int IMG_wind = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int InfoButton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int LaunchScreen = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int MapButton = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int OK = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int OrangeButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int RedButton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int splash = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int WaypointButton = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int GameView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int checkBox1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int checkBox2 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int checkBox3 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int checkBox4 = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageView2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imageView3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int imageView4 = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int imageView43 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int imageView5 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int imageView6 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int imageView7 = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout1 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout2 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout3 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout4 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout8 = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CustomLocationView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GameView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int InteractiveMapView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PreFlightCheckView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SplashScreen = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Theme_Main = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
